site_name: Portfolio

site_author: Jarosław Dulian


repo_name: JarekD4/ds_ai_portfolio
repo_url: https://github.com/JarekD4/ds_ai_portfolio




theme:
  name: material
  palette:
    primary: light blue

site_description: >-
    Portfolio moich projektów z Data Science i AI!


nav:
- Home Page: index.md
- Current project:
  - "visualization": visualization/index.md
- Previous projects:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "Audio Notes": audio_notes/index.md
  - "Find Friends": find_friends/index.md
  - "Halfmarathon Estimator": halfmarathon_estimator/index.md
  - "Welcome Survey": welcome_survey/index.md
  - "My Chatbot": my_chatbot/index.md
  - "Features Detective": features_detective/index.md
 
